{{ if .Values.longhorn.enabled -}}
apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: harvester-longhorn
{{- if .Values.storageClass.defaultStorageClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "{{ .Values.longhorn.persistence.reclaimPolicy }}"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "{{ .Values.longhorn.persistence.defaultClassReplicaCount }}"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
  migratable: "true"
{{- end -}}
